{% set name = "sagemaker-python-sdk" %}
{% set version = "3.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/sagemaker/sagemaker-{{ version }}.tar.gz
  sha256: b960660d354c9ac8b5bc15f41bb2dc272784b620754aceb7fae5e2ae08b89c33

build:
  noarch: python
  number: 0

requirements:
  run:
    - python >=3.9
    - sagemaker-core >=2.9.0,<3.0.0
    - sagemaker-train >=1.9.0,<2.0.0
    - sagemaker-serve >=1.9.0,<2.0.0
    - sagemaker-mlops >=1.9.0,<2.0.0

test:
  imports:
    - sagemaker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - mollyheamazon
    - mufaddal-rohawala
    - claytonparnell
    - nargokul
