{% set name = "sagemaker-python-sdk" %}
{% set version = "1.45.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz"
  sha256: 770a8b4d42b94d2e373937e3efc953dc545011f1bba86d8aeec508207f61f291

build:
  number: 0
  entry_points:
    - sagemaker=sagemaker.cli.main:main
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or py35 or py37]

requirements:
  host:
    - pip
    - python
  run:
    - boto3 >=1.10.32
    - docker-compose >=1.23.0
    - numpy >=1.9.0
    - protobuf >=3.1
    - protobuf3-to-dict >=0.1.5
    - pyyaml >=3.10,<5
    - python
    - requests >=2.20.0,<2.21
    - scipy >=0.19.0
    - urllib3 >=1.21,<1.25
    - smdebug-rulesconfig >=0.1.2

test:
  imports:
    - sagemaker
    - sagemaker.amazon
    - sagemaker.chainer
    - sagemaker.cli
    - sagemaker.local
    - sagemaker.mxnet
    - sagemaker.pytorch
    - sagemaker.rl
    - sagemaker.sklearn
    - sagemaker.sparkml
    - sagemaker.tensorflow
    - sagemaker.tensorflow.tensorflow_serving
    - sagemaker.tensorflow.tensorflow_serving.apis
    - sagemaker.workflow
    - sagemaker.xgboost
  commands:
    - sagemaker --help

about:
  home: "https://github.com/aws/sagemaker-python-sdk/"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "Open source library for training and deploying models on Amazon SageMaker."
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
