{% set name = "sagemaker-python-sdk" %}
{% set version = "2.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 55cbc4d42428d54d138c33d9385a15311555a7c1d4208c12785dc04f7989de31

build:
  number: 0
  entry_points:
    - sagemaker-upgrade-v2=sagemaker.cli.compatibility.v2.sagemaker_upgrade_v2:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - boto3 >=1.16.32
    - google-pasta
    - importlib-metadata >=1.4.0
    - numpy >=1.9.0
    - packaging >=20.0
    - protobuf >=3.1
    - protobuf3-to-dict >=0.1.5
    - python
    - smdebug-rulesconfig >=1.0.0
    - attrs

test:
  imports:
    - sagemaker
    - sagemaker.amazon
    - sagemaker.apiutils
    - sagemaker.automl
    - sagemaker.chainer
    - sagemaker.cli
    - sagemaker.cli.compatibility
    - sagemaker.cli.compatibility.v2
    - sagemaker.cli.compatibility.v2.modifiers
    - sagemaker.debugger
    - sagemaker.feature_store
    - sagemaker.lineage
    - sagemaker.local
    - sagemaker.model_monitor
    - sagemaker.mxnet
    - sagemaker.pytorch
    - sagemaker.rl
    - sagemaker.sklearn
    - sagemaker.spark
    - sagemaker.sparkml
    - sagemaker.tensorflow
    - sagemaker.workflow
    - sagemaker.xgboost
  commands:
    - sagemaker-upgrade-v2 --help

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
