{% set name = "sagemaker-python-sdk" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/sagemaker/sagemaker-{{ version }}.tar.gz
  sha256: b06c5e8de8db1c8e0e294a4700244b6c0ea95196b81be52e53dd044c7be1ecd2

build:
  {% if version.startswith('3.') %}
  script: |
    {{ PYTHON }} -m pip install "sagemaker-core>=2.0,<3.0"
    {{ PYTHON }} -m pip install "sagemaker-train<2.0"
    {{ PYTHON }} -m pip install "sagemaker-serve<2.0"
    {{ PYTHON }} -m pip install "sagemaker-mlops<2.0"
  {% else %}
  entry_points:
    - sagemaker-upgrade-v2=sagemaker.cli.compatibility.v2.sagemaker_upgrade_v2:main
  script: {{ PYTHON }} -m pip install . -vv
  {% endif %}
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    {% if not version.startswith('3.') %}
    - sagemaker-core >=1.0.17,<2.0.0
    - attrs >=24,<26
    - boto3 >=1.39.5,<2.0
    - cloudpickle >=2.2.1
    - google-pasta
    - numpy >=1.9.0,<2.0
    - protobuf >=3.12,<6.0
    - omegaconf >=2.2,<3
    - smdebug-rulesconfig ==1.0.1
    - importlib-metadata >=1.4.0,<7.0
    - packaging >=23.0,<25.0
    - pandas
    - fastapi
    - pathos
    - schema
    - pyyaml ~=6.0
    - jsonschema
    - platformdirs
    - tblib >=1.7.0,<4
    - urllib3 >=1.26.8,<3.0.0
    - uvicorn
    - requests
    - docker-py
    - tqdm
    - psutil
    - graphene >=3,<4
    {% endif %}

test:
  imports:
    {% if version.startswith('3.') %}
    - sagemaker.core
    - sagemaker.train
    - sagemaker.serve
    - sagemaker.mlops
    {% else %}
    - sagemaker
    - sagemaker.amazon
    - sagemaker.apiutils
    - sagemaker.automl
    - sagemaker.chainer
    - sagemaker.cli
    - sagemaker.cli.compatibility
    - sagemaker.cli.compatibility.v2
    - sagemaker.cli.compatibility.v2.modifiers
    - sagemaker.debugger
    - sagemaker.feature_store
    - sagemaker.lineage
    - sagemaker.local
    - sagemaker.model_monitor
    - sagemaker.mxnet
    - sagemaker.pytorch
    - sagemaker.rl
    - sagemaker.sklearn
    - sagemaker.spark
    - sagemaker.sparkml
    - sagemaker.tensorflow
    - sagemaker.workflow
    - sagemaker.xgboost
    {% endif %}
  commands:
    - pip check
    {% if not version.startswith('3.') %}
    - sagemaker-upgrade-v2 --help
    {% endif %}
  requires:
    - pip

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - mufaddal-rohawala
    - claytonparnell
    - zhaoqizqwang
