{% set name = "sagemaker-python-sdk" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/sagemaker/sagemaker-{{ version }}.tar.gz
  sha256: b06c5e8de8db1c8e0e294a4700244b6c0ea95196b81be52e53dd044c7be1ecd2

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - sagemaker-core >=2.0.0,<3.0.0
    - sagemaker-train <2.0.0
    - sagemaker-serve <2.0.0
    - sagemaker-mlops <2.0.0

test:
  imports:
    - sagemaker.core
    - sagemaker.train
    - sagemaker.serve
    - sagemaker.mlops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - liujiaor
    - knikure
    - jgoyani1
    - mufaddal-rohawala
    - claytonparnell
    - mxr-conda
    - rluria14
    - benhuff
    - oblute
