{% set name = "sagemaker-python-sdk" %}
{% set version = "3.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/sagemaker/sagemaker-{{ version }}.tar.gz
  sha256: e90f0a59f4a6e5b81be451f15280c6b24f3ee2e534655ef1b6132b7c3573f1e5

build:
  noarch: python
  number: 0

requirements:
  run:
    - python >=3.9
    - sagemaker-core >=2.13.0,<3.0.0
    - sagemaker-train >=1.13.0,<2.0.0
    - sagemaker-serve >=1.13.0,<2.0.0
    - sagemaker-mlops >=1.13.0,<2.0.0

test:
  imports:
    - sagemaker
    - sagemaker.core
    - sagemaker.train
    - sagemaker.serve
    - sagemaker.mlops

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - mollyheamazon
    - mufaddal-rohawala
    - claytonparnell
    - nargokul
