{% set name = "sagemaker-python-sdk" %}
{% set version = "2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f43e82367429b784bb36fdd3d5353666520987cfcbf319a306bea2e7bea248cd

build:
  number: 0
  entry_points:
    - sagemaker-upgrade-v2=sagemaker.cli.compatibility.v2.sagemaker_upgrade_v2:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - boto3 >=1.14.12
    - google-pasta
    - importlib-metadata >=1.4.0
    - numpy >=1.9.0
    - packaging >=20.0
    - protobuf >=3.1
    - protobuf3-to-dict >=0.1.5
    - python
    - smdebug-rulesconfig ==0.1.5

test:
  imports:
    - sagemaker
    - sagemaker.amazon
    - sagemaker.chainer
    - sagemaker.cli
    - sagemaker.local
    - sagemaker.mxnet
    - sagemaker.pytorch
    - sagemaker.rl
    - sagemaker.sklearn
    - sagemaker.sparkml
    - sagemaker.tensorflow
    - sagemaker.workflow
    - sagemaker.xgboost
  commands:
    - pip check
    - sagemaker-upgrade-v2 --help
  requires:
    - pip

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
