{% set name = "sagemaker-python-sdk" %}
{% set version = "2.239.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/sagemaker/sagemaker-{{ version }}.tar.gz
  sha256: e41c1d2ba0f83baf6e23629d966f4a19c06598472ed664b8ced14b1cf0e3da38

build:
  entry_points:
    - sagemaker-upgrade-v2=sagemaker.cli.compatibility.v2.sagemaker_upgrade_v2:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - sagemaker-core >=1.0.17,<2.0.0
    - attrs >=23.1.0,<24
    - boto3 >=1.35.75,<2.0
    - cloudpickle >=2.2.1
    - google-pasta
    - numpy >=1.9.0,<2.0
    - protobuf >=3.12,<6.0
    - omegaconf >=2.2,<2.4
    - smdebug-rulesconfig ==1.0.1
    - importlib-metadata >=1.4.0,<7.0
    - packaging >=20.0
    - pandas
    - smdebug-rulesconfig ==1.0.1
    - fastapi
    - pathos
    - schema
    - pyyaml ~=6.0
    - jsonschema
    - platformdirs
    - tblib >=1.7.0,<4
    - urllib3 >=1.26.8,<3.0.0
    - uvicorn
    - requests
    - docker-py
    - tqdm
    - psutil

test:
  imports:
    - sagemaker
    - sagemaker.amazon
    - sagemaker.apiutils
    - sagemaker.automl
    - sagemaker.chainer
    - sagemaker.cli
    - sagemaker.cli.compatibility
    - sagemaker.cli.compatibility.v2
    - sagemaker.cli.compatibility.v2.modifiers
    - sagemaker.debugger
    - sagemaker.feature_store
    - sagemaker.lineage
    - sagemaker.local
    - sagemaker.model_monitor
    - sagemaker.mxnet
    - sagemaker.pytorch
    - sagemaker.rl
    - sagemaker.sklearn
    - sagemaker.spark
    - sagemaker.sparkml
    - sagemaker.tensorflow
    - sagemaker.workflow
    - sagemaker.xgboost
  commands:
    - pip check
    - sagemaker-upgrade-v2 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/sagemaker-python-sdk/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Open source library for training and deploying models on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/
  dev_url: https://github.com/aws/sagemaker-python-sdk/

extra:
  recipe-maintainers:
    - liujiaor
    - knikure
    - jgoyani1
    - mufaddal-rohawala
    - claytonparnell
    - mxr-conda
    - rluria14
    - benhuff
    - oblute
