bot:
  automerge: true
  inspection: update-grayskull
  abi_migration_branches:
    - "v2.x"
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
